name: Sync Fork

on:
  workflow_dispatch: # manual trigger
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          owner: ultralight-ux
          base: master
          head: master